import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../theme';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

export const styles = StyleSheet.create({
  root: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    elevation: 9999,
  },
  shadowWrap: {
    position: "absolute",
    top: 0,
    left: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
  },
  surface: {
    overflow: "hidden",
    backgroundColor: "#000",
  },
  imageWrap: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  imageFallback: {
    width: "100%",
    height: "100%",
    backgroundColor: "transparent",
  },
  headerControls: {
    position: "absolute",
    left: 20,
    width: SCREEN_WIDTH - 40,
    height: 48,
    zIndex: 50,
  },
  headerControlsContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  headerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  headerSpacer: {
    width: 32,
    height: 32,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  closeButtonInner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonText: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 16,
    fontWeight: "600",
    marginTop: -2,
  },
  fullScreenScroll: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    zIndex: 10,
  },
  fixedHeaderContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.45,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 25,
  },
  touchCatcher: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT * 0.45,
    zIndex: 20,
  },
  pillBottom: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  sheetContentWrap: {
    flex: 1,
    minHeight: SCREEN_HEIGHT * 0.6,
    zIndex: 20,
    elevation: 20,
  },
  pillBackground: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(15, 15, 20, 0.45)",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: "hidden",
    gap: 10,
  },
  trailerButton: {
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  trailerCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(15, 15, 20, 0.45)",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  trailerLabel: {
    color: "#ffffffa9",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    marginTop: 8,
    textTransform: "uppercase",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  pillText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 12,
    fontWeight: "500",
    letterSpacing: 0.5,
  },
  pillDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  bottomSheetBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  blurContainer: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: "hidden",
  },
  scrollContent: {
    paddingTop: 32,
    paddingHorizontal: 24,
    zIndex: 95,
  },
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 100,
  },
  mutedText: {
    color: "#A0A0A5",
    marginTop: 16,
    fontSize: 14,
    fontWeight: "500",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 28,
    paddingTop: 100,
  },
  errorCard: {
    backgroundColor: "rgba(20, 18, 24, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    alignItems: "center",
    overflow: "hidden",
  },
  errorTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
  },
  errorText: {
    color: "#8E8D92",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 18,
  },
  retryBtn: {
    backgroundColor: theme.colors.accent,
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 20,
  },
  retryBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  titleContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  mainTitle: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.5,
    textAlign: "center",
    marginBottom: 8,
  },
  sheetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  seasonSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    gap: 6,
  },
  seasonText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 16,
    fontWeight: "500",
  },
  seasonIcon: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 10,
    marginTop: 2,
  },
  descriptionText: {
    color: "#A0A0A5",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  genreRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 32,
  },
  genreText: {
    color: "#A0A0A5",
    fontSize: 14,
  },
  imdbBadgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  imdbBadge: {
    backgroundColor: "#F5C518",
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 3,
  },
  imdbText: {
    color: "#000",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  ratingText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  linksError: {
    color: "#ffb4ab",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 16,
  },
  episodesList: {
    flex: 1,
  },
  empty: {
    color: "#666",
    textAlign: "center",
    paddingVertical: 40,
  },
  episodeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  episodeThumbContainer: {
    width: 160,
    height: 96,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#1f1f22",
  },
  episodeThumb: {
    width: "100%",
    height: "100%",
    opacity: 0.8,
  },
  playIconOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  playIconGlass: {
    width: 40,
    height: 40,
    borderRadius: 23,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  playIconGlassBlur: {
    width: 40,
    height: 40,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  playIconText: {
    color: "#fff",
    fontSize: 14,
    marginLeft: 3,
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
    letterSpacing: -0.2,
  },
  episodeInfo: {
    flex: 1,
    paddingLeft: 16,
    justifyContent: "center",
  },
  episodeMeta: {
    color: "#A0A0A5",
    fontSize: 12,
    marginBottom: 6,
  },
  episodeTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 22,
  },
  floatingDropdown: {
    position: "absolute",
    top: 42, // Right below the season selector button
    width: 200,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    zIndex: 100,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  dropdownItemSelected: {
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  dropdownItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  seasonNumberBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  seasonNumberBoxSelected: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.2)",
  },
  seasonNumberText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: "700",
  },
  seasonNumberTextSelected: {
    color: "#fff",
  },
  dropdownItemText: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 14,
    fontWeight: "600",
  },
  dropdownItemTextSelected: {
    color: "#fff",
    fontWeight: "700",
  },
  checkmark: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  recommendationsSection: {
    marginTop: 32,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    paddingTop: 24,
  },
  recommendationsTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 16,
  },
  recommendationsList: {
    paddingBottom: 8,
  },
  recPoster: {
    width: 100,
    height: 150,
    borderRadius: 12,
    backgroundColor: "#1f1f22",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  recPlaceholder: {
    backgroundColor: "#1f1f22",
  },
  recTitle: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    fontWeight: "500",
    marginTop: 6,
    lineHeight: 16,
  },
  seeMoreBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 20,
  },
  seeMoreText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  descriptionContainer: {
    marginBottom: 4,
  },
  expandedDetails: {
    marginTop: 8,
    marginBottom: 8,
    width: "100%",
  },
  detailLogo: {
    width: 140,
    height: 48,
    alignSelf: "center",
    marginBottom: 16,
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  metaGridItem: {
    flex: 1,
    minWidth: "28%",
  },
  metaGridItemFull: {
    width: "100%",
  },
  metaGridLabel: {
    color: "#8E8D92",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  metaGridValue: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "500",
  },
  castSection: {
    marginBottom: 24,
  },
  castScrollContainer: {
    position: "relative",
    overflow: "hidden",
  },
  castMaskedView: {
    width: "100%",
  },
  castList: {
    paddingLeft: 28,
    paddingRight: 16,
  },
  castCard: {
    width: 80,
    alignItems: "center",
    marginRight: 12,
  },
  castImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
    marginBottom: 6,
    backgroundColor: "#1c1b1c",
  },
  castPlaceholder: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  castInitials: {
    color: "#E5E2E3",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  castName: {
    color: "#fff",
    fontSize: 11,
    textAlign: "center",
  },
  castRole: {
    color: "#888",
    fontSize: 10,
    textAlign: "center",
    marginTop: 1,
  },
  castImdbBadge: {
    marginTop: 4,
    backgroundColor: "rgba(245, 197, 24, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(245, 197, 24, 0.35)",
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  castImdbBadgeText: {
    color: "#f5c518",
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  skeletonContainer: {
    paddingTop: 32,
    paddingHorizontal: 24,
    width: "100%",
  },
  skeletonTitle: {
    height: 36,
    borderRadius: 10,
    width: "75%",
    marginBottom: 12,
  },
  skeletonSeason: {
    height: 32,
    borderRadius: 16,
    width: 110,
    marginBottom: 20,
  },
  skeletonTagsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 20,
  },
  skeletonTag: {
    height: 18,
    borderRadius: 9,
    width: 70,
  },
  skeletonText: {
    height: 14,
    borderRadius: 4,
    marginBottom: 10,
  },
  skeletonHeader: {
    height: 22,
    borderRadius: 6,
    width: 90,
    marginBottom: 16,
  },
  skeletonRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    width: "100%",
  },
  skeletonThumb: {
    width: 140,
    height: 84,
    borderRadius: 10,
  },
  skeletonMetaWrap: {
    flex: 1,
    paddingLeft: 16,
    gap: 8,
  },
  skeletonMeta: {
    height: 10,
    width: 60,
    borderRadius: 3,
  },
  skeletonLine: {
    height: 14,
    width: "80%",
    borderRadius: 4,
  },
  skeletonDescLine: {
    height: 10,
    width: "95%",
    borderRadius: 3,
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
    justifyContent: "flex-end",
    zIndex: 10000,
    elevation: 10000,
  },
  sheet: {
    width: "100%",
    height: SCREEN_HEIGHT * 0.7,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(20, 18, 24, 0.45)",
  },
  sheetContent: {
    flex: 1,
    paddingBottom: 24,
    paddingHorizontal: 0,
    paddingTop: 8,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    width: "100%",
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  sheetCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetRefreshButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetVpnTip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(85, 128, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(85, 128, 255, 0.12)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
  },
  sheetVpnTipText: {
    color: "#8E8D92",
    fontSize: 10,
    flex: 1,
  },
  sheetListContainer: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    paddingHorizontal: 16,
  },
  sheetList: {
    flex: 1,
  },
  sheetRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.02)",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  sheetRowActive: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderColor: "rgba(255,255,255,0.15)",
  },
  sheetRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  sheetRadioActive: {
    borderColor: "#fff",
  },
  sheetRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#fff",
  },
  sheetRowInfo: {
    flex: 1,
  },
  sheetQualityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  sheetQuality: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 15,
    fontWeight: "600",
  },
  sheetQualityActive: {
    color: "#fff",
  },
  sheetBadge: {
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  sheetBadgeText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  sheetHost: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    fontWeight: "500",
  },
  sheetSubRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  sheetSubLabel: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
    fontWeight: "500",
  },
  sheetSubLangs: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 13,
    fontWeight: "500",
    flex: 1,
  },
  progressContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  progressTitle: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 13,
    fontWeight: "600",
  },
  progressChipsList: {
    gap: 8,
    paddingRight: 20,
  },
  progressChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    alignItems: "center",
    justifyContent: "center",
  },
  chipSearching: {
    borderColor: "rgba(85, 128, 255, 0.35)",
    backgroundColor: "rgba(85, 128, 255, 0.08)",
  },
  chipFound: {
    borderColor: "rgba(46, 204, 113, 0.45)",
    backgroundColor: "rgba(46, 204, 113, 0.12)",
  },
  chipNone: {
    borderColor: "rgba(255, 255, 255, 0.05)",
    backgroundColor: "rgba(255, 255, 255, 0.01)",
  },
  chipError: {
    borderColor: "rgba(255, 74, 125, 0.35)",
    backgroundColor: "rgba(255, 74, 125, 0.08)",
  },
  chipText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
  },
  chipTextNone: {
    color: "rgba(255, 255, 255, 0.35)",
  },
  chipTextFound: {
    color: "#2ecc71",
  },
  chipTextError: {
    color: "#ff4a7d",
  },
  vpnNoticeCard: {
    marginTop: 16,
    backgroundColor: "rgba(255, 74, 125, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 74, 125, 0.25)",
    borderRadius: 14,
    padding: 16,
    maxWidth: 300,
    alignItems: "center",
  },
  vpnNoticeTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 6,
    textAlign: "center",
  },
  vpnNoticeText: {
    color: "#A0A0A5",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
  },
  errorReasonCard: {
    marginTop: 12,
    backgroundColor: "rgba(255, 74, 125, 0.06)",
    borderRadius: 8,
    padding: 10,
    maxWidth: 280,
  },
  errorReasonText: {
    color: "#ffb4ab",
    fontSize: 11,
    textAlign: "center",
  },
  noSourcesContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  noSourcesText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 12,
    textAlign: "center",
  },
  noSourcesSubtext: {
    color: "#8e8d92",
    fontSize: 13,
    marginTop: 6,
    textAlign: "center",
    lineHeight: 18,
  },
  tabsContainer: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    position: "relative",
  },
  tabsScrollContent: {
    gap: 8,
    paddingHorizontal: 28, // extra room so first/last tab aren't hidden behind the fade overlays
  },
  tabsMaskedView: {
    width: "100%",
    height: 38,
  },
  sheetListMaskedView: {
    flex: 1,
    width: "100%",
  },
  tabButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tabButtonActive: {
    backgroundColor: "rgba(0, 71, 255, 0.15)",
    borderColor: "#0047FF",
  },
  tabText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#ffffff",
  },
  tabSubText: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 9,
    fontWeight: "500",
    marginTop: 2,
    maxWidth: 100,
  },
  langFilterRow: {
    width: "100%",
    paddingVertical: 8,
    marginBottom: 2,
  },
  langFilterScrollContent: {
    gap: 6,
    paddingHorizontal: 28,
  },
  langFilterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  langFilterChipActive: {
    backgroundColor: "rgba(0, 71, 255, 0.15)",
    borderColor: "#0047FF",
  },
  langFilterText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  langFilterTextActive: {
    color: "#ffffff",
  },
  skeletonStreamRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    marginBottom: 10,
  },
  skeletonRowInfo: {
    flex: 1,
  },
  skeletonQualityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  skeletonBadgeLarge: {
    width: 90,
    height: 18,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  skeletonBadgeSmall: {
    width: 45,
    height: 18,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  skeletonBadgeMedium: {
    width: 60,
    height: 18,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  dohNotice: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 6,
    marginTop: 4,
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: "rgba(85, 128, 255, 0.07)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(85, 128, 255, 0.18)",
  },
  dohNoticeText: {
    color: "#5580FF",
    fontSize: 11,
    flex: 1,
    lineHeight: 15,
  },
  listSearchingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    backgroundColor: "rgba(0, 71, 255, 0.05)",
    borderRadius: 8,
    marginHorizontal: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(0, 71, 255, 0.15)",
  },
  listSearchingText: {
    color: "#5580FF",
    fontSize: 12,
    fontWeight: "600",
  },
  activeOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  searchLoaderContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  searchLoaderText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 12,
  },
  searchLoaderSubtext: {
    marginTop: 8,
    textAlign: "center",
    lineHeight: 18,
  },
  torrentModalContainer: {
    flex: 1,
    backgroundColor: "rgba(5, 5, 5, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  torrentContentCard: {
    width: "85%",
    backgroundColor: "rgba(20, 18, 24, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    elevation: 8,
    shadowColor: "#0047FF",
    shadowOpacity: 0.15,
    shadowRadius: 16,
  },
  torrentTitleText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 18,
  },
  torrentSubTitleText: {
    color: "#8E8D92",
    fontSize: 13,
    marginTop: 6,
    textAlign: "center",
  },
  torrentProgressTrack: {
    width: "100%",
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 3,
    marginTop: 20,
    overflow: "hidden",
  },
  torrentProgressFill: {
    height: "100%",
    backgroundColor: "#0047FF",
    borderRadius: 3,
  },
  torrentStatsRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  torrentStatsText: {
    color: "#A0A0A5",
    fontSize: 12,
    fontWeight: "500",
  },
  torrentCancelButton: {
    marginTop: 24,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingVertical: 10,
    paddingHorizontal: 32,
    borderRadius: 20,
  },
  torrentCancelText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  torrentCancelButtonCustom: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    width: "100%",
  },
  torrentOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 5, 5, 0.88)",
    justifyContent: "center",
    alignItems: "center",
  },
  torrentGlassCard: {
    width: "88%",
    backgroundColor: "rgba(20, 18, 24, 0.93)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 32,
    padding: 24,
    alignItems: "center",
    overflow: "hidden",
    elevation: 12,
    shadowColor: "#0047FF",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
  },
  torrentGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 140,
  },
  torrentBadgeContainer: {
    backgroundColor: "rgba(0, 71, 255, 0.08)",
    borderWidth: 1.5,
    borderColor: "rgba(0, 71, 255, 0.25)",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  torrentBadgeText: {
    color: "#5580FF",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  torrentTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 4,
    paddingHorizontal: 12,
  },
  torrentSubtitle: {
    color: "#8E8D92",
    fontSize: 12,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 16,
  },
  torrentStatsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
    marginTop: 16,
    marginBottom: 12,
  },
  torrentStatBox: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  torrentStatLabel: {
    color: "#8E8D92",
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 4,
  },
  torrentStatLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  torrentStatValue: {
    color: "#E5E2E3",
    fontSize: 14,
    fontWeight: "700",
  },
  torrentInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
    marginBottom: 14,
  },
  torrentInfoBox: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  torrentInfoLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  torrentInfoLabel: {
    color: "#8E8D92",
    fontSize: 11,
    fontWeight: "600",
  },
  torrentInfoValue: {
    color: "#E5E2E3",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  torrentCaption: {
    color: "#8E8D92",
    fontSize: 11,
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  torrentCancelBtn: {
    backgroundColor: "rgba(255, 74, 125, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 74, 125, 0.22)",
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  torrentCancelBtnText: {
    color: "#ff4a7d",
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  torrentProgressCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 18,
    padding: 14,
    width: "100%",
    marginBottom: 12,
  },
  torrentProgressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  torrentProgressPercent: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
  },
  torrentProgressSpeed: {
    color: "#5580FF",
    fontSize: 12,
    fontWeight: "700",
  },
  torrentProgressBarTrack: {
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 3,
    overflow: "hidden",
    width: "100%",
  },
  torrentProgressBarFill: {
    height: "100%",
    backgroundColor: "#0047FF",
    borderRadius: 3,
  },
  circularContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 16,
    width: "100%",
  },
  circularTextWrapper: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  circularPercentText: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "800",
  },
  circularSpeedBadge: {
    backgroundColor: "rgba(0, 71, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(0, 71, 255, 0.2)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
  },
  circularSpeedText: {
    color: "#5580FF",
    fontSize: 10,
    fontWeight: "700",
  },
  accordionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.04)",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginTop: 8,
  },
  accordionHeaderActive: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.15)",
  },
  accordionTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    flex: 1,
  },
});